version: '3.1'
services:
  mysqldb:
    container_name: mysqldb
    image: mysql:latest
    command: --default-authentication-plugin=mysql_native_password
    volumes:
      - "./.mysql-data/db:/var/lib/mysql"
    restart: always
    ports:
      - 3306:3306
    environment:
      MYSQL_ROOT_PASSWORD: root
    networks:
      - apps-network
  phpmyadmin:
    image: phpmyadmin/phpmyadmin:latest
    restart: always
    environment:
        PMA_HOST: db
        PMA_USER: root
        PMA_PASSWORD: root
    ports:
        - "3000:80"
    networks:
        - apps-network

#Docker Networks
networks:
  apps-network:
    name: apps-network
    driver: bridge